name: nop.sol.Stack
version: "3.7"
services:
    nop.sol.web:
        container_name: nop.sol.web
        build:
            context: ../..
            dockerfile: ./containers/devcontainers/Nop.Web/Dockerfile
            args:
                IDE_USER: "${USER:-defaultuser}"  # Default to 'defaultuser' if USER is not set
                IDE_UID: ${USERID:-1000}         # Default to '1000' if USERID is not set
                IDE_GID: ${GROUPID:-1000}        # Default to '1000' if GROUPID is not set
                DEBUG: "${DEBUG:-false}"         # Default to 'false' if DEBUG is not set
        user: "${USER:-defaultuser}"
        environment:
            - USER=${USER:-defaultuser}
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
            - DEBUG=${DEBUG:-false}             # Pass DEBUG to the container environment
        ports:
            - "8080:8080"
        depends_on:
            nop.sol.mssql:                       # Updated service name to match changes
                condition: service_started
                required: true
        networks:
            - nop.sol.net                        # Removed trailing colon
        # volumes:
        #     - type: bind
        #       source: ../src
        #       target: /workspace/src
        #     - type: bind
        #       source: ../.devcontainer
        #       target: /workspace/.devcontainer
    nop.sol.mssql:                             # Updated service name to match changes
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: nop.sol.mssql            # Updated container name to match changes
        environment:
            SA_PASSWORD: "${MSSQL_SA_PASSWORD:-YourStrong@Passw0rd}"  # Default password if not set
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        networks:
            - nop.sol.net                        # Updated network name to match changes
        ports:
            - "1443:1443"  # Expose SQL Server port

networks:
  nop.sol.net:
    driver: bridge
